from commands.step import Step

cycle_steps = [
    Step.WAIT_FOR_ROBOT_READY_STATE,
    Step.WAIT_FOR_FRONTEND_CYCLE_START,
    Step.MOVE_ROBOT_TO_RESISTANCE_STATION,
    Step.READ_RESISTANCE,
    Step.MOVE_ROBOT_TO_COMMAND_PANEL,
    Step.READ_LETTERS,
    Step.TO_FIRST_PUCK_AND_GRAB_FIRST_PUCK,
    Step.GRIP_PUCK,
    Step.TO_FIRST_CORNER_AND_RELEASE_FIRST_PUCK,
    Step.RELEASE_PUCK,
    Step.TO_SECOND_PUCK_AND_GRAB_SECOND_PUCK,
    Step.GRIP_PUCK,
    Step.TO_SECOND_CORNER_AND_RELEASE_SECOND_PUCK,
    Step.RELEASE_PUCK,
    Step.TO_THIRD_PUCK_AND_GRAB_THIRD_PUCK,
    Step.GRIP_PUCK,
    Step.TO_THIRD_CORNER_AND_RELEASE_THIRD_PUCK,
    Step.RELEASE_PUCK,
    Step.MOVE_ROBOT_TO_SQUARE_CENTER,
    Step.END_CYCLE
]
