const START_CYCLE = 'START_CYCLE';
const RESET_CYCLE = 'RESET_CYCLE';
const SOCKET_ROBOT_CONSUMPTION = 'SOCKET_ROBOT_CONSUMPTION';
const SOCKET_TABLE_IMAGE = 'SOCKET_TABLE_IMAGE';
const SOCKET_RESISTANCE = 'SOCKET_RESISTANCE';
const SOCKET_PUCK_COLORS = 'SOCKET_PUCK_COLORS';
const SOCKET_PUCK_FIRST_CORNER = 'SOCKET_PUCK_FIRST_CORNER';
const SOCKET_PLANNED_TRAJECTORY_COORDINATES =
  'SOCKET_PLANNED_TRAJECTORY_COORDINATES';
const SOCKET_REAL_TRAJECTORY_COORDINATE = 'SOCKET_REAL_TRAJECTORY_COORDINATE';
const SOCKET_GRIP_STATE = 'SOCKET_GRIP_STATE';
const SOCKET_CURRENT_STEP = 'SOCKET_CURRENT_STEP';

export {
  START_CYCLE,
  RESET_CYCLE,
  SOCKET_ROBOT_CONSUMPTION,
  SOCKET_TABLE_IMAGE,
  SOCKET_RESISTANCE,
  SOCKET_PUCK_COLORS,
  SOCKET_PUCK_FIRST_CORNER,
  SOCKET_PLANNED_TRAJECTORY_COORDINATES,
  SOCKET_REAL_TRAJECTORY_COORDINATE,
  SOCKET_GRIP_STATE,
  SOCKET_CURRENT_STEP,
};
